### ISSUE TITLE
Graphic issue in some menu after update

### ISSUE THREAD

**Issue by chiccofra** [buyanov/noExtLinks#13]
There are some graphic issue with new version, I setup the module and now it works, except this logout/login page: https://gitravel.it/component/users/?view=login&Itemid=101

I don't know how to white list this page...
Thanks

**Comment by buyanov** [comment]
Hi! Give me 5 minutes =)

**Comment by buyanov** [comment]
You need to remove the commented links in the header, or temporary disable <noindex> option in plugin.

I'll solve this problem in the next update

**Comment by chiccofra** [comment]
Thank you I wait for the next update

Francesco

 

Da: Danila Buyanov [mailto:notifications@github.com] 
Inviato: venerdì 28 aprile 2017 12:25
A: buyanov/noExtLinks <noExtLinks@noreply.github.com>
Cc: chiccofra <info@gitravel.it>; Author <author@noreply.github.com>
Oggetto: Re: [buyanov/noExtLinks] Graphic issue in some menu after update (#13)

 

You need to remove the commented links in the header, or temporary disable option in plugin.

I'll solve this problem in the next update
