### ISSUE TITLE
PHP7 error

### ISSUE THREAD

**Issue by ramonlopez23** [buyanov/noExtLinks#9]
Hi, I use your excellent plug-in in Joomla 3.6.5 and PHP7 and the following warning is coming up and populating my site error-log.

PHP Warning:  First parameter must either be an object or the name of an existing class in /home2/xxx/public_html/xxx.com/plugins/system/noextlinks/noextlinks.php on line 51

Are you planing to update the plugin for compatibility with PHP7?
Thanks

**Comment by chris001** [comment]
What version of the plugin are you using? Your bug with the line 51 doesn't match the current version here.

**Comment by ramonlopez23** [comment]
This is what my joomla back end shows:
System - NO External Links
Site	Plugin	1.6.7	Agust 2012	Buyanov Danila

**Comment by chris001** [comment]
@ramonlopez23  That should fix it.  As soon as @buyanov reviews the fix, accepts it and copies it to his private gitlab server, the new version will appear inside your joomla site's Extensions Manage Update page.

**Comment by ramonlopez23** [comment]
Thank you!

I'l be keeping and eye for it.

**Comment by buyanov** [comment]
Thx @chris001 for fixes 👍
the last version was placed to https://gitlab.s74.org/saity74/plg_noextlinks
Gitlab block update repo ((( because "update" is reserved path...

**Comment by ramonlopez23** [comment]
HI! My wife just updated without telling me the plug in to version 1.7.1, and now her site is giving an error:
Warning: array_map(): Argument #2 should be an array in /home2/******/public_html/******.com/plugins/system/noextlinks/noextlinks.php on line 161

Warning: Only arrays and Traversables can be unpacked in /home2/*****/public_html/*****.com/plugins/system/noextlinks/noextlinks.php on line 168

Thanks for your continued efforts on improving this excellent plugin.

**Comment by buyanov** [comment]
Hi! Thx! Give me 5 minutes :) I fix it

**Comment by buyanov** [comment]
@ramonlopez23 
https://gitlab.s74.org/saity74/plg_noextlinks/repository/archive.zip?ref=1.7.2

Thanks for your request!

**Comment by ramonlopez23** [comment]
You guy's are amazing. That fix the error! 
We need more people like you developing for Joomla. 

Thanks 

Ps: would it be possible in a future update integrate an icon that would show that the link go to a external page? Just a thought 

Again, thanks for your hard work!
